In [26]:
import numpy as np 

In [27]:
l= [1,2,3,4]


In [28]:
ar= np.array(l)

In [29]:
type(ar)

numpy.ndarray

In [30]:

ar1= np.array([[1,2],[3,4]])

In [31]:
ar1[0]

array([1, 2])

In [32]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [33]:
np.array(b)

array([[1, 2, 3, 4]])

In [34]:
c=np.array([1,2,3,4])

In [35]:
a=c  # ISSE SHALLOW COPY HOJAEGA 

In [36]:
a[0]

1

In [37]:
a[0]=10 

In [38]:
c

array([10,  2,  3,  4])

In [39]:
d = np.copy(c)

In [40]:
d

array([10,  2,  3,  4])

In [41]:
d[1]=1001

In [42]:
d

array([  10, 1001,    3,    4])

In [43]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [62]:
np.fromfunction(lambda i,j : j*i , (5,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.],
       [ 0.,  2.,  4.,  6.],
       [ 0.,  3.,  6.,  9.],
       [ 0.,  4.,  8., 12.]])

In [63]:
iterable = (i*i for i in range(5))

In [64]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [66]:
np.ndim(b)

2

In [67]:
b.shape

(1, 4)

In [69]:
range(5)

range(0, 5)

In [70]:
list(range(5))

[0, 1, 2, 3, 4]

In [71]:
np.arange(2.3,5.9)

array([2.3, 3.3, 4.3, 5.3])

In [72]:
np.arange(1.4,5.6,.4)

array([1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. , 5.4])

In [73]:
list(np.fromfunction(lambda i,j : j*i , (5,4) ))

[array([0., 0., 0., 0.]),
 array([0., 1., 2., 3.]),
 array([0., 2., 4., 6.]),
 array([0., 3., 6., 9.]),
 array([ 0.,  4.,  8., 12.])]

In [77]:
np.ones((3, 2,2,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]])

In [79]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [81]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])