In [1]:
import numpy as np

In [3]:
arr =np.array([4,5,4,5,6,72,3,3,455,5,6,6])
arr

array([  4,   5,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [4]:
np.sort(arr)

array([  3,   3,   4,   4,   5,   5,   5,   6,   6,   6,  72, 455])

In [5]:
np.searchsorted(arr,34)

12

In [8]:
np.searchsorted(arr,3)

0

In [9]:
np.where(arr>6)

(array([5, 8], dtype=int64),)

In [10]:
np.extract(arr>3,arr)

array([  4,   5,   4,   5,   6,  72, 455,   5,   6,   6])

In [11]:
# Numpy -Copies & Views  

In [12]:
arr

array([  4,   5,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [13]:
a =np.copy(arr)

In [17]:
b= arr.view()

In [18]:
b

array([  4,   5,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [19]:
b[0] =67

In [20]:
b

array([ 67,   5,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [21]:
a

array([  4,   5,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [22]:
# Numpy - Matrix Library

In [23]:
import numpy.matlib as nm

In [28]:
nm.zeros((5,2))

matrix([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
# Numpy - Linear Algebra

In [42]:
arr1 = np.random.randint([[2,3] , [4,5]])
arr1

array([[0, 2],
       [0, 3]])

In [41]:
arr2 = np.random.randint([[5,3],[2,5]])
arr2

array([[3, 0],
       [1, 2]])

In [43]:
np.dot(arr1,arr2)

array([[2, 4],
       [3, 6]])