In [2]:
#Numpy - Array Manipulation

In [3]:
import numpy as np 

In [4]:
arr = np.random.randint(2,6,(2,6))
arr

array([[3, 4, 3, 4, 5, 4],
       [2, 3, 4, 4, 3, 5]])

In [5]:
arr.reshape(6,2)

array([[3, 4],
       [3, 4],
       [5, 4],
       [2, 3],
       [4, 4],
       [3, 5]])

In [6]:
arr.reshape(6,-934)

array([[3, 4],
       [3, 4],
       [5, 4],
       [2, 3],
       [4, 4],
       [3, 5]])

In [7]:
arr2 =arr.flatten()
arr2

array([3, 4, 3, 4, 5, 4, 2, 3, 4, 4, 3, 5])

In [8]:
arr2.ndim

1

In [9]:
arr3= np.expand_dims(arr2,axis=1)
arr3

array([[3],
       [4],
       [3],
       [4],
       [5],
       [4],
       [2],
       [3],
       [4],
       [4],
       [3],
       [5]])

In [10]:
arr4 =np.squeeze(arr3)
arr4

array([3, 4, 3, 4, 5, 4, 2, 3, 4, 4, 3, 5])

In [11]:
arr4.repeat(2)

array([3, 3, 4, 4, 3, 3, 4, 4, 5, 5, 4, 4, 2, 2, 3, 3, 4, 4, 4, 4, 3, 3,
       5, 5])

In [12]:
np.roll(arr4,3)

array([4, 3, 5, 3, 4, 3, 4, 5, 4, 2, 3, 4])

In [13]:
np.diag(arr4)

array([[3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5]])

In [14]:
m1 = np.random.randint(0,5,(4,4))
m1

array([[3, 2, 4, 2],
       [0, 2, 0, 3],
       [2, 1, 0, 1],
       [2, 2, 2, 2]])

In [15]:
m2= np.random.randint(0,4,(4,4))
m2

array([[2, 3, 0, 2],
       [1, 2, 2, 2],
       [2, 1, 1, 2],
       [0, 2, 0, 0]])

In [16]:
m2 & m1

array([[2, 2, 0, 2],
       [0, 2, 0, 2],
       [2, 1, 0, 0],
       [0, 2, 0, 0]])

In [17]:
arr= np.array(['sudh','Kumar'])
arr

array(['sudh', 'Kumar'], dtype='<U5')

In [18]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [19]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [20]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [21]:
np.sin(arr3)

array([[ 0.14112001],
       [-0.7568025 ],
       [ 0.14112001],
       [-0.7568025 ],
       [-0.95892427],
       [-0.7568025 ],
       [ 0.90929743],
       [ 0.14112001],
       [-0.7568025 ],
       [-0.7568025 ],
       [ 0.14112001],
       [-0.95892427]])

In [23]:
np.power(arr3,3)

array([[ 27],
       [ 64],
       [ 27],
       [ 64],
       [125],
       [ 64],
       [  8],
       [ 27],
       [ 64],
       [ 64],
       [ 27],
       [125]], dtype=int32)

In [24]:
np.var(arr3)

0.7222222222222223