In [1]:
import numpy as np 

In [2]:
l= [1,2,3,4]


In [3]:
ar= np.array(l)

In [4]:
type(ar)

numpy.ndarray

In [5]:

ar1= np.array([[1,2],[3,4]])

In [6]:
ar1[0]

array([1, 2])

In [7]:
b=np.matrix(l)
b

matrix([[1, 2, 3, 4]])

In [8]:
np.array(b)

array([[1, 2, 3, 4]])

In [9]:
c=np.array([1,2,3,4])

In [10]:
a=c  # ISSE SHALLOW COPY HOJAEGA matlab by reference

In [11]:
a[0]

1

In [12]:
a[0]=10 

In [13]:
c

array([10,  2,  3,  4])

In [14]:
d = np.copy(c)

In [15]:
d

array([10,  2,  3,  4])

In [16]:
d[1]=1001

In [17]:
d

array([  10, 1001,    3,    4])

In [18]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
np.fromfunction(lambda i,j : j*i , (5,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.],
       [ 0.,  2.,  4.,  6.],
       [ 0.,  3.,  6.,  9.],
       [ 0.,  4.,  8., 12.]])

In [20]:
iterable = (i*i for i in range(5))

In [21]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [32]:
np.fromstring('234 235', sep=' ')

array([234., 235.])

In [36]:
np.fromstring('23,45',sep=',')

array([23., 45.])

In [22]:
np.ndim(b)

2

In [23]:
b.shape

(1, 4)

In [24]:
range(5)

range(0, 5)

In [25]:
list(range(5))

[0, 1, 2, 3, 4]

In [26]:
np.arange(2.3,5.9)

array([2.3, 3.3, 4.3, 5.3])

In [27]:
np.arange(1.4,5.6,.4)

array([1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. , 5.4])

In [28]:
list(np.fromfunction(lambda i,j : j*i , (5,4) ))

[array([0., 0., 0., 0.]),
 array([0., 1., 2., 3.]),
 array([0., 2., 4., 6.]),
 array([0., 3., 6., 9.]),
 array([ 0.,  4.,  8., 12.])]

In [29]:
np.ones((3, 2,2,6))

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]])

In [30]:
np.linspace(2,5,10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [31]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [40]:
arr=np.random.randn(3,4) # randint 

In [38]:
import pandas as pd

In [44]:
df= pd.DataFrame(arr,columns=['l','k','p','i'])

In [42]:
df

0         1         2         3
0  0.108130 -0.446134  1.920295  0.204049
1 -0.462268 -0.335111  0.547016  0.212939
2  1.039387 -0.433081  0.997067  1.620351

In [45]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [58]:
arr1= np.random.rand(3,4)
arr1

array([[0.71386263, 0.34778625, 0.14226535, 0.74572015],
       [0.11083042, 0.91417129, 0.18200421, 0.6218001 ],
       [0.56040182, 0.46410988, 0.96844256, 0.9420646 ]])

In [59]:
arr1.reshape(6,2)

array([[0.71386263, 0.34778625],
       [0.14226535, 0.74572015],
       [0.11083042, 0.91417129],
       [0.18200421, 0.6218001 ],
       [0.56040182, 0.46410988],
       [0.96844256, 0.9420646 ]])

In [60]:
arr1[0:3,1]

array([0.34778625, 0.91417129, 0.46410988])

In [61]:
arr2= np.random.randint(5,10,(5,5))

In [62]:
arr2

array([[6, 9, 9, 9, 6],
       [9, 5, 6, 9, 7],
       [7, 9, 9, 7, 6],
       [7, 6, 9, 7, 5],
       [6, 8, 7, 5, 5]])

In [63]:
arr2>6

array([[False,  True,  True,  True, False],
       [ True, False, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True, False,  True,  True, False],
       [False,  True,  True, False, False]])

In [64]:
arr2[arr2>6]

array([9, 9, 9, 9, 9, 7, 7, 9, 9, 7, 7, 9, 7, 8, 7])

In [65]:
arr2[2:4,(1,3)]

array([[9, 7],
       [6, 7]])

In [66]:
arr1 =np.random.randint(1,3,(4,4))
arr2 =np.random.randint(1,3,(4,4))

In [69]:
arr3=arr1+arr2
arr1
arr2

array([[2, 2, 1, 1],
       [2, 1, 2, 2],
       [1, 1, 1, 2],
       [1, 1, 1, 2]])

In [68]:
arr3

array([[4, 4, 2, 3],
       [4, 3, 3, 3],
       [2, 2, 2, 4],
       [2, 2, 2, 4]])

In [70]:
arr3**2


array([[16, 16,  4,  9],
       [16,  9,  9,  9],
       [ 4,  4,  4, 16],
       [ 4,  4,  4, 16]])

In [71]:
np.sqrt(arr3)

array([[2.        , 2.        , 1.41421356, 1.73205081],
       [2.        , 1.73205081, 1.73205081, 1.73205081],
       [1.41421356, 1.41421356, 1.41421356, 2.        ],
       [1.41421356, 1.41421356, 1.41421356, 2.        ]])

In [72]:
np.exp(arr3)

array([[54.59815003, 54.59815003,  7.3890561 , 20.08553692],
       [54.59815003, 20.08553692, 20.08553692, 20.08553692],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 , 54.59815003],
       [ 7.3890561 ,  7.3890561 ,  7.3890561 , 54.59815003]])

In [73]:
np.log10(arr3)

array([[0.60205999, 0.60205999, 0.30103   , 0.47712125],
       [0.60205999, 0.47712125, 0.47712125, 0.47712125],
       [0.30103   , 0.30103   , 0.30103   , 0.60205999],
       [0.30103   , 0.30103   , 0.30103   , 0.60205999]])